#ifndef SEARCH_ALGORITHMS_FOCAL_SEARCH_H
#define SEARCH_ALGORITHMS_FOCAL_SEARCH_H

/*
  Focal search (Pearl and Kim 1982) with K-focal batches and an optional
  preferred-operator sub-list.

    f = open_eval (an admissible g + h);  f_min = min_{n in OPEN} f(n);
    FOCAL = {n in OPEN | f(n) <= w * f_min}, ordered by focal_eval.

  Each step expands up to k nodes of FOCAL (nodes generated by preferred
  operators of pref_eval first, if pref_eval is given) with w * f_min fixed
  for the batch; then f_min is recomputed and the nodes of OPEN with
  f <= w * f_min are moved into FOCAL. A node that entered FOCAL stays there
  (sticky FOCAL): the bound f <= w * f_min <= w * C* held when it entered.
  The goal test is applied to the selected node. A strictly cheaper path
  updates an open node and reopens a closed one (reopen_closed, default
  true), recomputing f and deciding anew between FOCAL and the rest of OPEN.

  All queues are integer-keyed FIFO buckets whose entries store the (g, f) of
  their insertion; an entry is current iff its node is open with that g and
  f and on the side (FOCAL or not) the queue belongs to. Entries of closed or
  reinserted nodes are skipped when they reach the front, never by scanning
  a bucket. Only the admissible open_eval decides dead ends: an infinite
  focal estimate keeps the node in FOCAL with the lowest priority (key
  INT_MAX), so count_f and in_focal always agree with the queues.
*/

#include "../per_state_information.h"
#include "../search_algorithm.h"

#include <deque>
#include <map>
#include <memory>
#include <optional>
#include <vector>

class Evaluator;

namespace plugins {
class Feature;
}

namespace focal_search {
class FocalSearch : public SearchAlgorithm {
    const bool reopen_closed_nodes;
    const int k;
    std::shared_ptr<Evaluator> open_evaluator;       // f = g + h, admissible
    std::shared_ptr<Evaluator> focal_evaluator;      // orders FOCAL
    std::shared_ptr<Evaluator> preferred_evaluator;  // optional
    const double w;
    long long scaled_w;   // w * WEIGHT_SCALE; w has at most six decimal digits

    struct Entry {
        StateID id;
        int g;
        int f;
    };
    using Queue = std::map<int, std::deque<Entry>>;   // key -> FIFO bucket

    Queue open_list;    // OPEN \ FOCAL, keyed by f
    Queue focal_list;   // FOCAL nodes, keyed by focal_eval
    Queue focal_pref;   // FOCAL nodes generated by preferred operators, keyed by focal_eval
    std::map<int, int> count_f;   // number of FOCAL nodes per f value

    PerStateInformation<int> f_value;            // f of the latest insertion
    PerStateInformation<bool> in_focal;          // open and currently in FOCAL
    PerStateInformation<bool> generated_by_pref; // reached through a preferred operator

    int f_min;   // exact minimum f over OPEN after the last step (-1: OPEN empty)

    std::vector<Evaluator *> path_dependent_evaluators;

    long long preferred_expansions;
    long long stale_entries_skipped;

    bool within_bound(int f) const;   // f <= w * f_min, exact
    bool is_current_entry(const SearchNode &node, const State &state,
                          const Entry &entry, bool expected_in_focal) const;
    // Remove stale entries from the front of a queue; return its first current entry, if any.
    std::optional<Entry> current_front(Queue &queue, bool expected_in_focal);
    static void pop_front(Queue &queue);

    // Insert an open node with values g, f: FOCAL if f <= w * f_min, else open_list.
    void insert_node(const State &state, int g, int f, EvaluationContext &eval_context);
    void insert_into_focal(const State &state, int g, int f, EvaluationContext &eval_context);
    void remove_from_focal(const State &state);   // expanded or reinserted
    void update_f_min_and_fill_focal();
    std::optional<SearchNode> select_node(bool &from_preferred);

protected:
    virtual void initialize() override;
    virtual SearchStatus step() override;

public:
    explicit FocalSearch(const plugins::Options &opts);
    virtual ~FocalSearch() = default;

    virtual void print_statistics() const override;
};

extern void add_options_to_feature(plugins::Feature &feature);
}

#endif
