#include "focal_search.h"

#include "../plugins/plugin.h"

using namespace std;

namespace plugin_focal {
class FocalSearchFeature : public plugins::TypedFeature<SearchAlgorithm, focal_search::FocalSearch> {
public:
    FocalSearchFeature() : TypedFeature("focal_search") {
        document_title("Focal search");
        document_synopsis(
            "Bounded-suboptimal focal search (Pearl and Kim 1982): open_eval "
            "(an admissible f = g + h) defines f_min and "
            "FOCAL = {n in OPEN | f(n) <= w * f_min}; focal_eval orders FOCAL. "
            "Optionally, states generated by preferred operators of pref_eval "
            "form a sub-list of FOCAL that is expanded first. With k > 1, each "
            "step expands up to k nodes with w * f_min fixed (K-focal search). "
            "Every expanded node satisfied f <= w * f_min when it entered FOCAL, "
            "so the plan costs at most w times the optimal cost.");

        add_option<shared_ptr<Evaluator>>(
            "open_eval",
            "admissible evaluator defining f = g + h, e.g. sum([g(), lmcut()])");
        add_option<shared_ptr<Evaluator>>(
            "focal_eval",
            "evaluator ordering FOCAL");
        add_option<shared_ptr<Evaluator>>(
            "pref_eval",
            "evaluator providing preferred operators; states generated by them "
            "form a FOCAL sub-list that is expanded first (optional)",
            plugins::ArgumentInfo::NO_DEFAULT);
        add_option<double>(
            "w",
            "suboptimality bound, 1 <= w <= 1000, with at most six decimal digits",
            "2.0",
            plugins::Bounds("1.0", "1000.0"));
        add_option<int>(
            "k",
            "nodes expanded per step with w * f_min fixed (K-focal search); 1 is standard focal search",
            "1",
            plugins::Bounds("1", "infinity"));
        add_option<bool>(
            "reopen_closed",
            "reopen closed nodes when a strictly cheaper path is found. Required "
            "for the w bound; with false only parent pointers are updated, as in "
            "eager_search.",
            "true");
        focal_search::add_options_to_feature(*this);

        document_note(
            "Implementation",
            "All queues are integer-keyed FIFO buckets whose entries store the "
            "(g, f) of their insertion; entries of closed or reinserted nodes are "
            "skipped when they reach the front. After each step f_min is "
            "recomputed (first current entry of the open list and the f counts "
            "of FOCAL) and the open-list nodes with f <= w * f_min move into "
            "FOCAL. A node that entered FOCAL stays there even if f_min later "
            "decreases through a reopened node; the bound held when it entered.");
    }
};

static plugins::FeaturePlugin<FocalSearchFeature> _plugin;
}
