#include "focal_search.h"
#include "search_common.h"

#include "../plugins/plugin.h"

using namespace std;

namespace plugin_focal {
class FocalSearchFeature : public plugins::TypedFeature<SearchAlgorithm, focal_search::FocalSearch> {
public:
    FocalSearchFeature() : TypedFeature("focal_search") {
        document_title("Focal search");
        document_synopsis(
            "Focal search with optional preferred-operator prioritization. "
            "States generated by preferred operators of pref_eval are inserted "
            "into a focal_pref sub-list and expanded before non-preferred states. "
            "Supports K-Focal Search (k>1) and w-suboptimality bound.");

        add_list_option<shared_ptr<Evaluator>>("evals", "evaluators", "[]");

        add_option<shared_ptr<Evaluator>>(
            "open_eval",
            "admissible evaluator for the OPEN list ordering (f = g + h)",
            plugins::ArgumentInfo::NO_DEFAULT);

        add_option<shared_ptr<Evaluator>>(
            "focal_eval",
            "evaluator for ordering within FOCAL",
            plugins::ArgumentInfo::NO_DEFAULT);

        add_option<shared_ptr<Evaluator>>(
            "pref_eval",
            "evaluator that provides preferred operators; states generated by "
            "preferred ops are prioritized inside FOCAL (default: focal_eval)",
            plugins::ArgumentInfo::NO_DEFAULT);

        add_option<double>(
            "w",
            "suboptimality bound w >= 1.0",
            "2.0");

        add_option<int>(
            "k",
            "number of nodes expanded per step (K-Focal Search); k=1 is standard focal search",
            "1");

        focal_search::add_options_to_feature(*this);
    }

    virtual shared_ptr<focal_search::FocalSearch> create_component(
        const plugins::Options &options, const utils::Context &) const override {

        plugins::Options options_copy(options);
        options_copy.set("reopen_closed", false);

        return make_shared<focal_search::FocalSearch>(options_copy);
    }
};

static plugins::FeaturePlugin<FocalSearchFeature> _plugin;
}
