#include "typed_focal_search.h"
#include "search_common.h"

#include "../plugins/plugin.h"

using namespace std;

namespace plugin_typed_focal {

class TypedFocalSearchFeature
    : public plugins::TypedFeature<SearchAlgorithm, typed_focal_search::TypedFocalSearch> {
public:
    TypedFocalSearchFeature() : TypedFeature("typed_focal_search") {
        document_title("Typed Focal Search");
        document_synopsis(
            "Focal search with type-based bucket selection inside FOCAL. "
            "States are grouped into buckets by their focal heuristic value (h_focal). "
            "The bucket with the lowest h_focal is always selected; within that bucket "
            "a state is chosen uniformly at random, providing diversity on plateaus. "
            "An optional preferred-operator list (typed_pref) can be extracted with "
            "priority controlled by pref_balance. "
            "The w-suboptimality guarantee is preserved: only states with "
            "f(n) <= w * f_min are kept in FOCAL; open_eval must be admissible.");

        add_list_option<shared_ptr<Evaluator>>("evals", "evaluators", "[]");

        add_option<shared_ptr<Evaluator>>(
            "open_eval",
            "admissible evaluator for OPEN ordering and FOCAL admission (f = g + h)",
            plugins::ArgumentInfo::NO_DEFAULT);

        add_option<shared_ptr<Evaluator>>(
            "focal_eval",
            "evaluator used as the bucket key inside FOCAL (need not be admissible)",
            plugins::ArgumentInfo::NO_DEFAULT);

        add_option<shared_ptr<Evaluator>>(
            "pref_eval",
            "evaluator providing preferred operators; states generated by preferred "
            "ops go to a separate typed_pref list. Disabled if omitted.",
            plugins::ArgumentInfo::NO_DEFAULT);

        add_option<double>(
            "w",
            "suboptimality bound w >= 1.0",
            "2.0");

        add_option<int>(
            "k",
            "expansions per step; k=1 is standard TFS, k>1 gives K-TFS batch behaviour",
            "1");

        add_option<int>(
            "pref_balance",
            "controls extraction order between typed_focal and typed_pref: "
            "0 = always typed_focal (pref_eval ignored for routing), "
            "1 = alternate one from each list per expansion, "
            "2 = typed_pref first, fall back to typed_focal when empty",
            "0");

        add_option<int>(
            "random_seed",
            "seed for the random number generator used inside buckets",
            "2011");

        typed_focal_search::add_options_to_feature(*this);
    }

    virtual shared_ptr<typed_focal_search::TypedFocalSearch> create_component(
        const plugins::Options &options, const utils::Context &) const override {

        plugins::Options options_copy(options);
        options_copy.set("reopen_closed", false);
        return make_shared<typed_focal_search::TypedFocalSearch>(options_copy);
    }
};

static plugins::FeaturePlugin<TypedFocalSearchFeature> _plugin;

}  // namespace plugin_typed_focal
