#include "focal_search.h"
#include "search_common.h"

#include "../plugins/plugin.h"

using namespace std;

namespace plugin_focal {
class FocalSearchFeature : public plugins::TypedFeature<SearchAlgorithm, focal_search::FocalSearch> {
public:
    FocalSearchFeature() : TypedFeature("focal_search") {
        document_title("Focal search");
        document_synopsis(
            "Focal search with optional preferred-operator prioritization. "
            "States generated by preferred operators of pref_eval are inserted "
            "into a focal_pref sub-list and expanded before non-preferred states. "
            "Supports K-Focal Search (k>1) and w-suboptimality bound.");

        add_list_option<shared_ptr<Evaluator>>("evals", "evaluators", "[]");

        add_option<shared_ptr<Evaluator>>(
            "open_eval",
            "admissible evaluator for the OPEN list ordering (f = g + h)");

        add_option<shared_ptr<Evaluator>>(
            "focal_eval",
            "evaluator for ordering within FOCAL");

        add_option<shared_ptr<Evaluator>>(
            "pref_eval",
            "evaluator that provides preferred operators; states generated by "
            "preferred ops are prioritized inside FOCAL (optional)",
            plugins::ArgumentInfo::NO_DEFAULT);

        add_option<double>(
            "w",
            "suboptimality bound w >= 1.0",
            "2.0",
            plugins::Bounds("1.0", "infinity"));

        add_option<int>(
            "k",
            "number of nodes expanded per step (K-Focal Search); k=1 is standard focal search",
            "1",
            plugins::Bounds("1", "infinity"));

        add_option<bool>(
            "reopen_closed",
            "reopen closed nodes when a strictly cheaper path is found (required "
            "for the w bound with inconsistent heuristics)",
            "true");

        focal_search::add_options_to_feature(*this);
    }
};

static plugins::FeaturePlugin<FocalSearchFeature> _plugin;
}
