#include "discrepancy_focal_search.h"
#include "search_common.h"

#include "../plugins/plugin.h"

using namespace std;

namespace plugin_discrepancy_focal {

class DiscrepancyFocalSearchFeature
    : public plugins::TypedFeature<SearchAlgorithm, discrepancy_focal_search::DiscrepancyFocalSearch> {
public:
    DiscrepancyFocalSearchFeature() : TypedFeature("discrepancy_focal_search") {
        document_title("Discrepancy Focal Search");
        document_synopsis(
            "Bounded-suboptimal search alternating three views of the same "
            "FOCAL list (f <= w * f_min): a min-h_focal heap (exploitation), "
            "a min-h_focal heap over states generated by preferred operators, "
            "and buckets keyed by path discrepancy (number of times along the "
            "current best path that the successor was not a minimum-h_focal "
            "sibling), where a bucket is chosen uniformly at random and the "
            "min-h state within it is expanded. "
            "The w-suboptimality guarantee is preserved independently of the "
            "alternation policy; open_eval must be admissible.");

        add_list_option<shared_ptr<Evaluator>>("evals", "evaluators", "[]");

        add_option<shared_ptr<Evaluator>>(
            "open_eval",
            "admissible evaluator for OPEN ordering and FOCAL admission (f = g + h)",
            plugins::ArgumentInfo::NO_DEFAULT);

        add_option<shared_ptr<Evaluator>>(
            "focal_eval",
            "evaluator ordering the FOCAL views and defining discrepancies "
            "(minimum among siblings)",
            plugins::ArgumentInfo::NO_DEFAULT);

        add_option<shared_ptr<Evaluator>>(
            "pref_eval",
            "evaluator providing preferred operators; states generated by "
            "preferred ops additionally enter the focal_pref view. "
            "Disabled if omitted ('p' rotation slots then fall back to 'h').",
            plugins::ArgumentInfo::NO_DEFAULT);

        add_option<double>(
            "w",
            "suboptimality bound w >= 1.0",
            "2.0");

        add_option<int>(
            "k",
            "expansions per step; k=1 is standard, k>1 gives batch behaviour",
            "1");

        add_option<discrepancy_focal_search::Rotation>(
            "rotation",
            "round-robin expansion order over the views "
            "(h = min-h heap, p = preferred heap, d = discrepancy buckets). "
            "Empty views fall back to the remaining ones.",
            "hpd");

        add_option<int>(
            "random_seed",
            "seed for the random number generator",
            "2011");

        discrepancy_focal_search::add_options_to_feature(*this);
    }

    virtual shared_ptr<discrepancy_focal_search::DiscrepancyFocalSearch> create_component(
        const plugins::Options &options, const utils::Context &) const override {

        plugins::Options options_copy(options);
        options_copy.set("reopen_closed", false);
        return make_shared<discrepancy_focal_search::DiscrepancyFocalSearch>(options_copy);
    }
};

static plugins::FeaturePlugin<DiscrepancyFocalSearchFeature> _plugin;

static plugins::TypedEnumPlugin<discrepancy_focal_search::Rotation> _rotation_enum_plugin({
        {"h",   "min-h_focal heap only (classic focal search)"},
        {"p",   "preferred-operator heap only"},
        {"d",   "discrepancy buckets only"},
        {"hp",  "alternate h and preferred"},
        {"hd",  "alternate h and discrepancy"},
        {"pd",  "alternate preferred and discrepancy"},
        {"hpd", "alternate h, preferred and discrepancy (default)"},
    });

}  // namespace plugin_discrepancy_focal
