#include "typed_focal_hg_search.h"
#include "search_common.h"

#include "../plugins/plugin.h"

using namespace std;

namespace plugin_typed_focal_hg {

class TypedFocalHGSearchFeature
    : public plugins::TypedFeature<SearchAlgorithm, typed_focal_hg_search::TypedFocalHGSearch> {
public:
    TypedFocalHGSearchFeature() : TypedFeature("typed_focal_hg_search") {
        document_title("Typed Focal HG Search");
        document_synopsis(
            "Focal search with (h_focal, g) typed bucket selection inside FOCAL. "
            "States are grouped into buckets by their (h_focal, g) pair — the same "
            "type definition used by Type WA*. A bucket is chosen uniformly at "
            "random (like TypeWA*'s typed step), then a state is chosen uniformly "
            "at random within that bucket, providing diversity across both heuristic "
            "quality and search depth. "
            "The w-suboptimality guarantee is preserved: only states with "
            "f(n) <= w * f_min are kept in FOCAL; open_eval must be admissible.");

        add_list_option<shared_ptr<Evaluator>>("evals", "evaluators", "[]");

        add_option<shared_ptr<Evaluator>>(
            "open_eval",
            "admissible evaluator for OPEN ordering and FOCAL admission (f = g + h)",
            plugins::ArgumentInfo::NO_DEFAULT);

        add_option<shared_ptr<Evaluator>>(
            "focal_eval",
            "evaluator used as the h component of the bucket key (h_focal, g)",
            plugins::ArgumentInfo::NO_DEFAULT);

        add_option<shared_ptr<Evaluator>>(
            "pref_eval",
            "evaluator providing preferred operators; states generated by preferred "
            "ops go to a separate typed_pref list. Disabled if omitted.",
            plugins::ArgumentInfo::NO_DEFAULT);

        add_option<double>(
            "w",
            "suboptimality bound w >= 1.0",
            "2.0");

        add_option<int>(
            "k",
            "expansions per step; k=1 is standard, k>1 gives batch behaviour",
            "1");

        add_option<int>(
            "pref_balance",
            "controls extraction order between typed_focal and typed_pref: "
            "0 = always typed_focal, "
            "1 = alternate one from each list per expansion, "
            "2 = typed_pref first, fall back to typed_focal when empty",
            "0");

        add_option<int>(
            "random_seed",
            "seed for the random number generator",
            "2011");

        typed_focal_hg_search::add_options_to_feature(*this);
    }

    virtual shared_ptr<typed_focal_hg_search::TypedFocalHGSearch> create_component(
        const plugins::Options &options, const utils::Context &) const override {

        plugins::Options options_copy(options);
        options_copy.set("reopen_closed", false);
        return make_shared<typed_focal_hg_search::TypedFocalHGSearch>(options_copy);
    }
};

static plugins::FeaturePlugin<TypedFocalHGSearchFeature> _plugin;

}  // namespace plugin_typed_focal_hg
