#ifndef SEARCH_ALGORITHMS_TYPE_MULTI_FOCAL_SEARCH_H
#define SEARCH_ALGORITHMS_TYPE_MULTI_FOCAL_SEARCH_H

/*
  Type Multi Focal Search (type_mfs)

  Bounded-suboptimal focal search (Pearl and Kim 1982) with
    - an admissible heuristic h that defines f = g + h and the bound
      FOCAL = {n in OPEN | f(n) <= w * f_min},  f_min = min_{n in OPEN} f(n);
    - one or more inadmissible "focal" heuristics, each ordering its own copy
      of FOCAL (multi focal search); focal steps use the lists in rotation;
    - type-based exploration steps exactly as in Type-WA* (Cohen, Valenzano
      and McIlraith, IJCAI 2021): choose uniformly at random one of the types
      (h, g) that have nodes in FOCAL, then uniformly at random a node of that
      type;
    - an optional preferred list (off by default): FOCAL nodes generated by a
      preferred operator, ordered by f, that focal steps use first.

  Steps alternate strictly: odd steps are focal steps (preferred list if it has
  a node, otherwise the next focal list in the rotation), even steps are type
  steps, so half of the expansions are type-based. The goal test is applied to
  the selected node. A strictly cheaper path updates an open node and reopens
  a closed one, recomputing h and deciding anew whether the node belongs to
  FOCAL or to the rest of OPEN. Every expanded node satisfied f <= w * f_min
  when it entered FOCAL, hence any returned plan costs at most w * optimal.

  Data structures (all with the same shape, and the same lazy handling of
  stale entries, as type_based_wastar):
    - open_list: nodes of OPEN that are not in FOCAL, integer-keyed FIFO
      buckets by f. Its first current entry gives the minimum f outside FOCAL.
    - focal_lists[i]: FOCAL nodes, FIFO buckets keyed by focal evaluator i.
    - preferred_list: FOCAL nodes generated by preferred operators, keyed by f.
    - Type buckets (h, g) of FOCAL nodes grouped by f = g + h in a sorted map;
      discarding stale entries from the lowest-f buckets gives the minimum f
      inside FOCAL. The type step samples these buckets like Type-WA*.
    Every entry stores the (g, h) of its insertion; an entry is current iff its
    node is open with that g, h and FOCAL membership. Entries of closed or
    reinserted nodes are skipped when drawn and removed lazily, never by
    scanning a whole bucket.
  After each expansion f_min is recomputed from the two minima and every
  node of open_list with f <= w * f_min is moved into FOCAL (all focal lists,
  its type bucket, and the preferred list if applicable).
*/

#include "../per_state_information.h"
#include "../search_algorithm.h"
#include "../utils/rng.h"

#include <deque>
#include <map>
#include <memory>
#include <optional>
#include <unordered_map>
#include <utility>
#include <vector>

class Evaluator;

namespace plugins {
class Feature;
}

namespace type_multi_focal_search {
class TypeMultiFocalSearch : public SearchAlgorithm {
    std::shared_ptr<Evaluator> h_evaluator;
    std::vector<std::shared_ptr<Evaluator>> focal_evaluators;
    // Empty list: the preferred list is not used.
    std::vector<std::shared_ptr<Evaluator>> preferred_operator_evaluators;
    const double w;
    long long scaled_w;   // w * WEIGHT_SCALE; w has at most six decimal digits.
    const int random_seed;
    utils::RandomNumberGenerator rng;

    struct Entry {
        StateID id;
        int g;
        int h;
    };
    using Queue = std::map<int, std::deque<Entry>>;   // key -> FIFO bucket

    Queue open_list;                  // OPEN \ FOCAL, keyed by f = g + h
    std::vector<Queue> focal_lists;   // FOCAL, one list per focal evaluator
    Queue preferred_list;             // FOCAL nodes from preferred operators, keyed by f

    using TypeKey = std::pair<int, int>;   // (h, g)
    struct TypeKeyHash {
        std::size_t operator()(const TypeKey &key) const noexcept {
            return std::hash<long long>()(
                (static_cast<long long>(key.first) << 32) ^
                static_cast<unsigned int>(key.second));
        }
    };
    struct TypeBucket {
        int h;
        int g;
        std::vector<StateID> entries;
    };
    std::map<int, std::vector<TypeBucket>> buckets_by_f;   // FOCAL types grouped by f
    std::unordered_map<TypeKey, int, TypeKeyHash> bucket_position;

    PerStateInformation<int> latest_h;          // h of the latest insertion (-1: none)
    PerStateInformation<bool> in_focal;         // latest insertion went to FOCAL
    PerStateInformation<bool> preferred_state;  // reached through a preferred operator

    int f_min;   // exact minimum f over OPEN after the last step (-1: OPEN empty)
    long long step_counter;
    std::size_t next_focal_list;

    std::vector<Evaluator *> path_dependent_evaluators;

    // Statistics.
    long long preferred_expansions;
    std::vector<long long> focal_expansions;   // per focal list
    long long type_expansions;
    long long stale_entries_skipped;
    long long stale_type_entries;

    bool use_preferred() const {return !preferred_operator_evaluators.empty();}
    bool within_bound(int f) const;   // f <= w * f_min, exact
    bool is_current_entry(const SearchNode &node, const State &state,
                          int g, int h, bool expected_in_focal) const;

    // Insert a node that is open with values g, h: FOCAL if f <= w * f_min, else open_list.
    void insert_node(const State &state, int g, int h, EvaluationContext &eval_context);
    void insert_into_focal(const State &state, int g, int h, EvaluationContext &eval_context);

    TypeBucket &get_or_create_bucket(int h, int g);
    void remove_bucket(int f, int position);

    // Remove stale entries from the front of a queue; return its first current entry, if any.
    std::optional<Entry> current_front(Queue &queue, bool expected_in_focal);
    int clean_and_get_focal_f_min();   // via the lowest-f type buckets
    void update_f_min_and_fill_focal();

    std::optional<SearchNode> select_focal_node(std::string &origin);
    std::optional<SearchNode> select_type_node();

protected:
    virtual void initialize() override;
    virtual SearchStatus step() override;

public:
    explicit TypeMultiFocalSearch(const plugins::Options &opts);
    virtual ~TypeMultiFocalSearch() = default;

    virtual void print_statistics() const override;
};

extern void add_options_to_feature(plugins::Feature &feature);
}

#endif
