#ifndef SEARCH_ALGORITHMS_TYPED_FOCAL_SEARCH_H
#define SEARCH_ALGORITHMS_TYPED_FOCAL_SEARCH_H

#include "../open_list.h"
#include "../search_algorithm.h"
#include "../utils/rng.h"

#include <map>
#include <memory>
#include <vector>

class Evaluator;

namespace plugins {
class Feature;
}

namespace typed_focal_search {

/*
 * Typed Focal Search (TFS / K-TFS)
 *
 * FOCAL is organized as typed buckets keyed by h_focal value.
 * Extraction always picks the bucket with the lowest h_focal (best),
 * then selects uniformly at random within that bucket — providing
 * diversity on plateaus without sacrificing the w-suboptimality bound.
 *
 * Two FOCAL lists:
 *   typed_focal : states generated by non-preferred operators
 *   typed_pref  : states generated by preferred operators (pref_eval)
 *
 * pref_balance controls extraction order:
 *   0 — always typed_focal (typed_pref not used)
 *   1 — alternate: typed_focal, typed_pref, typed_focal, typed_pref, ...
 *   2 — typed_pref first; fall back to typed_focal when typed_pref is empty
 *
 * Suboptimality guarantee: only states with f(n) ≤ w·f_min are in FOCAL;
 * open_eval must be an admissible evaluator (f = g + h_admissible).
 */
class TypedFocalSearch : public SearchAlgorithm {
    const int k;             // expansions per step (k=1: standard TFS)
    const int pref_balance;  // 0 / 1 / 2
    const double w;

    std::shared_ptr<Evaluator> open_evaluator;
    std::shared_ptr<Evaluator> focal_evaluator;
    std::shared_ptr<Evaluator> preferred_evaluator;  // nullptr = disabled

    // Typed FOCAL buckets: key = h_focal value (map iterates ascending = best first)
    std::map<int, std::vector<StateID>> typed_focal;
    std::map<int, std::vector<StateID>> typed_pref;

    // Standard OPEN list for states with f > w·f_min, ordered by open_eval
    std::unique_ptr<StateOpenList> open_list;

    PerStateInformation<int>  f_value;         // f = g + h_open, stored at generation
    PerStateInformation<int>  h_focal_val;     // h_focal, stored at generation
    PerStateInformation<bool> in_focal;        // true iff in typed_focal or typed_pref
    PerStateInformation<bool> generated_by_pref;

    std::map<int, int> count_f;                // f-value distribution in FOCAL
    int f_min;

    bool next_from_pref;                       // alternation state for pref_balance=1
    utils::RandomNumberGenerator rng;

    std::vector<Evaluator *> path_dependent_evaluators;

    // Returns true if this (is_pref, pref_balance) combination routes to typed_pref
    bool use_pref_list(bool is_pref) const { return is_pref && pref_balance > 0; }

    void insert_typed(const State &s, int hf, bool is_pref);
    void remove_typed(const State &s);
    StateID extract_typed(bool from_pref);

    void start_f_value_statistics(EvaluationContext &eval_context);

protected:
    virtual void initialize() override;
    virtual SearchStatus step() override;

public:
    explicit TypedFocalSearch(const plugins::Options &opts);
    virtual ~TypedFocalSearch() = default;

    virtual void print_statistics() const override;
    void dump_search_space() const;
};

extern void add_options_to_feature(plugins::Feature &feature);

}  // namespace typed_focal_search

#endif
